subjects = ["C","C++","Python","Basic",4,4]
subjects.append("Toc")
subjects.insert(2,"Os")
#subjects.remove("Basic")
#subjects.sort()
#subjects.reverse()
#subjects.pop()
#subjects2=subjects.copy()
#print(len(subjects))
#pos = subjects.index("Python")
print(subjects.count(4))